### ISSUE TITLE
IsValidDynamicActor OOB error

### ISSUE THREAD

**Issue by kvanningsen** [emmet-jones/actor-streamer#4]
```pawn
if (!(0 <= actorid < MAX_DYNAMIC_ACTORS) || (!s_DynamicActors[actorid][e_iSlotUsed]))
```

These should be separate checks, otherwise you would get an array index OOB error if actorid is not in the range.

**Comment by emmet-jones** [comment]
It checks if the actor ID is out of range:

if (!(0 <= actorid < MAX_DYNAMIC_ACTORS)

The code after the "||" part is only called if the above statement is false. So in reality an OOB error is impossible in this case.

**Comment by kvanningsen** [comment]
Oh, that's something new. Closed.
